export const Products = [
  {
    id: 1,
    image: "assets/default-image.png",
    name: "Shampoo",
    category_id: 1,
    description: "This is the cool shampoo",
    price: "Rs. 400",
  },
  {
    id: 1,
    image: "assets/default-image.png",
    name: "Shampoo",
    category_id: 1,
    description: "This is the cool shampoo",
    price: "Rs. 400",
  },
  {
    id: 1,
    image: "assets/default-image.png",
    name: "Shampoo",
    category_id: 1,
    description: "This is the cool shampoo",
    price: "Rs. 400",
  },
  {
    id: 1,
    image: "assets/default-image.png",
    name: "Shampoo",
    category_id: 1,
    description: "This is the cool shampoo",
    price: "Rs. 400",
  },
  {
    id: 1,
    image: "assets/default-image.png",
    name: "Shampoo",
    category_id: 1,
    description: "This is the cool shampoo",
    price: "Rs. 400",
  },
  {
    id: 2,
    image: "assets/default-image.png",
    name: "Soap",
    category_id: 2,
    description: "This is the cool soap",
    price: "Rs. 400",
  },
  {
    id: 3,
    image: "assets/default-image.png",
    name: "Bikes",
    category_id: 15,
    description: "This is the cool bikes",
    price: "Rs. 400",
  },
  {
    id: 4,
    image: "assets/default-image.png",
    name: "Cricket Bag",
    category_id: 16,
    description: "This is the cool cricket bag",
    price: "Rs. 400",
  },
  {
    id: 5,
    image: "assets/default-image.png",
    name: "Cricket Bat",
    category_id: 16,
    description: "This is the cool cricket bat",
    price: "Rs. 400",
  },
  {
    id: 6,
    image: "assets/default-image.png",
    name: "Frying Pan",
    category_id: 8,
    description: "This is the cool frying pan",
    price: "Rs. 400",
  },
];
